# Generated by Django 5.0.6 on 2026-05-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
